### ISSUE TITLE
Client Errors on renown/all

### ISSUE THREAD

**Issue by Mudpuppy12** [cailleach1310/ares-renown-plugin#2]
When issuing a renown/all the following error occurs:

2025-05-07 00:22:35 +0000 ERROR - Error in renown/all: client=965 error=undefined method `titleize' for an instance of Hash backtrace=["/home/ares/aresmush/plugins/renown/templates/renown_all_template.rb:26:in `titles'", "(erubis):4:in `block in evaluate'", "/home/ares/.rvm/gems/ruby-3.3.6/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'", "/home/ares/.rvm/gems/ruby-3.3.6/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'", "/home/ares/aresmush/engine/aresmush/templates/erb_template_renderer.rb:16:in `render'", "/home/ares/aresmush/plugins/renown/commands/renown_all.rb:17:in `handle'", "/home/ares/aresmush/engine/aresmush/plugin/command_handler.rb:25:in `on_command'", "/home/ares/aresmush/engine/aresmush/commands/dispatcher.rb:98:in `block (3 levels) in on_command'", "/home/ares/aresmush/engine/aresmush/error_block.rb:6:in `with_error_handling'", "/home/ares/aresmush/engine/aresmush/commands/dispatcher.rb:93:in `block (2 levels) in on_command'"]

**Comment by Mudpuppy12** [comment]
Same issue with

renown/org foo

2025-05-07 00:28:07 +0000 ERROR - Error in renown/group foo: client=965 error=undefined method `titleize' for an instance of Hash backtrace=["/home/ares/aresmush/plugins/renown/templates/renown_group_template.rb:14:in `org_title'", "(erubis):2:in `block in evaluate'", "/home/ares/.rvm/gems/ruby-3.3.6/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'", "/home/ares/.rvm/gems/ruby-3.3.6/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'", "/home/ares/aresmush/engine/aresmush/templates/erb_template_renderer.rb:16:in `render'", "/home/ares/aresmush/plugins/renown/commands/renown_view_group.rb:34:in `handle'", "/home/ares/aresmush/engine/aresmush/plugin/command_handler.rb:25:in `on_command'", "/home/ares/aresmush/engine/aresmush/commands/dispatcher.rb:98:in `block (3 levels) in on_command'", "/home/ares/aresmush/engine/aresmush/error_block.rb:6:in `with_error_handling'", "/home/ares/aresmush/engine/aresmush/commands/dispatcher.rb:93:in `block (2 levels) in on_command'"]

**Comment by Mudpuppy12** [comment]
```
---
renown:
  achievements:
    renown_leading:
      type: story
      message: Was announced as leading in the specified time span in the regular
        bbpost.
    renown_favorite:
      type: story
      message: Overall leader at the end of the season.
  cron_message_category: Announcements
  cron_message_title: Favorite of the Week
  cron_regular_check:
    day_of_week:
    - Mon
    hour:
    - 6
    minute:
    - 15
  cron_renown_days: 7
  org_links: false
  org_page_postfix: {}
  org_page_prefix: {}
  renown_group: {}
  renown_members: {}
  renown_title: Renown
  shortcuts: {}
  standard_types:
  - type: Freeform
    points: 0
  visible: true
  web_renown_total_fields: {}
```
